### ISSUE TITLE
GitLab (or other) support

### ISSUE THREAD

**Issue by EternalBlack** [ekonstantinidis/gitify#150]
Would be really handy to have support for other platforms like GitLab, BitBucket or Gogs.
Is something like this planned?

**Comment by klousiaj** [comment]
:+1: would love to see Bitbucket added to this.

**Comment by nonameolsson** [comment]
I would love to have support for Bitbucket!

**Comment by ekonstantinidis** [comment]
In my opinion, this should be a a fork of Gitify and I can't think of a good way that will allow the fork to stay up to date with the original one(ie. if I add a new feature to Gitify) since GitLab's and Bitbucket's REST Apis will be different from the GitHub's one. I would be really happy to help anyone interested though!
