### ISSUE TITLE
Gitify shows a blank screen

### ISSUE THREAD

**Issue by ankushdharkar** [ekonstantinidis/gitify#159]
If the application is running for a while, or sometimes when the computer resumes from sleep, a blank screen is displayed. The banner notifications show up as expected, but clicking them leads to a white blank screen

**Comment by ekonstantinidis** [comment]
Hello @ankushdharkar! I'm currently rewriting gitify(almost from scratch) and plan to release version 1.0.0 in the next couple of weeks. Since I won't release a patch for the current version, I will close this one for now and let me know if you get the same issue when Version 1.0.0 is released so we can reopen this issue. Thank you for reporting!

**Comment by ankushdharkar** [comment]
This issue continues in the new release

**Comment by ankushdharkar** [comment]
@ekonstantinidis: This issue continues in the new release
![screen shot 2016-06-24 at 2 27 19 pm](https://cloud.githubusercontent.com/assets/1935403/16351074/cbf0ba2c-3a17-11e6-8ea9-59f47b45c52c.png)

**Comment by joeybaker** [comment]
I just ran into this after attempting to build the project myself. I reverted the `brew` version and still the same problem. Maybe there's a cache corrupted somewhere?

**Comment by manosim** [comment]
@joeybaker Can you try to press `cmd+alt+i` and check for any logs?

Ps. New major update coming soon 😄

**Comment by joeybaker** [comment]
Whoops… sorry, I would but I just got things cleared up with:

```sh
rm -rf ~/Library/preferences/com.electron.gitify.* ~/Library/Application\ Support/gitify
npm run release
```
