### ISSUE TITLE
'On Click, Mark as Read' setting not being respected

### ISSUE THREAD

**Issue by aioue** [ekonstantinidis/gitify#181]
I have this setting turned off (`x` showing), but clicking causes the link to disappear from gitify.

**Comment by ekonstantinidis** [comment]
Hello @aioue!

#### What is actually happening
By default when you click on a notification on GitHub.com the notification is mark as read.
When you click on a notification on gitify, most of the times(depending if it's a comment, a release etc), GitHub will mark it as read automatically.

#### Why there is the `On Click, Mark as Read`
Since the default functionality is to mark notifications as read(happens by GitHub, not Gitify), we added this setting so if github does not mark it as read, gitify will do it for you. This is related to #101.

It may sound weird but I don't think we can do anything about it. In my opinion, the best option would be for GitHub to provide an `html_url` field for each notification in the API so that everything will be read on click and avoid confusion.
