### ISSUE TITLE
Issues missing from window.

### ISSUE THREAD

**Issue by octalmage** [ekonstantinidis/gitify#208]
I've had this issue for the last few weeks (maybe longer). I get a notification for an issue, I click the tray icon and the issue isn't listed in the window. I can then bring up my notification center and see the issue listed there, and when I click it, it brings up the window but the issue is still missing. 

Here are my settings: 

![](https://cloudup.com/cASoEA-GLgo+)

It seems like I only see about half of my issues.

**Comment by octalmage** [comment]
Could it be that GitHub is marking the notification as read when I view it, and it's getting removed from the view? I just tested this by viewing a PR in my browser without using Gitify, and it disappeared. I'm not familiar with the notification API though.

**Comment by ekonstantinidis** [comment]
Yes that is correct. Github marks notifications as read when you go to the right url. Unfortunately that doesn't happen if you don't have the exact url (ie. `#comment-12345`) so that is why we added the option "On Click, Mark as Read". Using this gitify will automatically read all notifications as read.

Ps. This is an old version of Gitify - version 1.0.0 is out for a while now ([Link](https://github.com/ekonstantinidis/gitify/releases/tag/1.0.0)) 😄
