### ISSUE TITLE
Better linking (to comment instead of to issue)

### ISSUE THREAD

**Issue by caske33** [ekonstantinidis/gitify#42]
Not sure if this is the api or not, but when I click on github.com on my notification, I go to the comment on the issue that's new. While in gitify, I go to the issue (but not the new comment)

**Comment by ekonstantinidis** [comment]
So according to the GitHub docs about [notifications](https://developer.github.com/v3/activity/notifications/#list-your-notifications) for each notifications we get the following:

      {
        "id": "1",
        "repository": {
          "id": 1296269,
          ......
        },
        "subject": {
          "title": "Greetings",
          "url": "https://api.github.com/repos/octokit/octokit.rb/issues/123",
          "latest_comment_url": "https://api.github.com/repos/octokit/octokit.rb/issues/comments/123",
          "type": "Issue"
        },
        "reason": "subscribed",
        "unread": true,
        ......
      }

Currently we are using `subject.url` to link to the github page. Maybe we could use `subject.latest_comment_url`? Not sure if it's going to work since the url is about the API but we can give it a try and see if it works correctly. [Notification component](https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/notification.js#L19).

**Comment by caske33** [comment]
But it probably depends on the type of notification. Does that also work for new issues?

**Comment by ekonstantinidis** [comment]
I'm not sure. I'm checking my notifications but I will have to receive one that is a new issue to check!

**Comment by ekonstantinidis** [comment]
@caske33 Just tried with a notification and it's a 404. https://github.com/facebook/react/issues/comments/107253724
It does work with PRs but not with Issues. So if we find a way to make the above url to open the issue with the latest comment that would be great. Then all we have to do is check what happens if is a new issue which sounds doable.

**Comment by ekonstantinidis** [comment]
Looks like this one requires further research. So will leave it out of the next release.

**Comment by ekonstantinidis** [comment]
Will ask from the GitHub if we can have an `html_url` attribute in the API like they provide for other things. Until then it would be better if we keep it clean? Example (`data.owner.html_url`):

    [
      {
        "id": "1",
        "repository": {
          "id": 1296269,
          "owner": {
            "login": "octocat",
            "id": 1,
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
          },
          "name": "Hello-World",
          "full_name": "octocat/Hello-World",
          "description": "This your first repo!",
          "private": false,
          "fork": false,
          "url": "https://api.github.com/repos/octocat/Hello-World",
          "html_url": "https://github.com/octocat/Hello-World"
        },
        "subject": {
          "title": "Greetings",
          "url": "https://api.github.com/repos/octokit/octokit.rb/issues/123",
          "latest_comment_url": "https://api.github.com/repos/octokit/octokit.rb/issues/comments/123",
          "type": "Issue"
        },
        "reason": "subscribed",
        "unread": true,
        "updated_at": "2014-11-07T22:01:45Z",
        "last_read_at": "2014-11-07T22:01:45Z",
        "url": "https://api.github.com/notifications/threads/1"
      }
    ]
