### ISSUE TITLE
Desktop notifications for old notifications

### ISSUE THREAD

**Issue by JakeSidSmith** [ekonstantinidis/gitify#61]
Currently if you have a lot of notifications, the GitHub API only returns the most recent.

Marking one of these recent notifications as read and then refreshing causes GitHub to send a "new" notification (but is actually a much older one).

Gitify then gives a desktop notification for this old notification as if it were new.

**Comment by ekonstantinidis** [comment]
I guess it kinda makes sense to display a notification since the user is not aware of hidden notifications - the GitHub api displays only 50 notifications per request(paginated). Either way if someone has more than 50 notifications I guess he won't use gitify and notifications in general that much? There's also the "Participating" option in settings which can limit the number of notications!

**Comment by ulope** [comment]
> Either way if someone has more than 50 notifications I guess he won't use gitify and notifications in general that much?

I can very much assure you that this statement is false. I use gitify daily despite:
![](https://ds.ulo.pe/wkG9Gtggg2.jpg)

The re-occuring notifications for old issues are pretty annoying.
