### ISSUE TITLE
Uncaught (in promise) Error: Unauthorized

### ISSUE THREAD

**Issue by mdibaiee** [ekonstantinidis/gitify#96]
Hey, I just cloned and built Gitify using `npm build`.

So I `npm start`, I login and I get: "Oops something went wrong. Couldn't get your notifications"

console:
```
[58426:0919/201607:INFO:CONSOLE(26876)] "Uncaught (in promise) Error: Unauthorized", source: file:///Users/mahdi/Documents/Workshop/github/gitify/build/js/app.js (26876)
[58426:0919/201710:INFO:CONSOLE(0)] "Refused to set unsafe header "User-Agent"", source: file:///Users/mahdi/Documents/Workshop/github/gitify/index.html#/notifications (0)
```

btw I tried revoking GitHub access and authorizing again, no change.

**Comment by ekonstantinidis** [comment]
Hi @mdibaiee! This is happening because the **client secret key** is missing from the file  `/src/js/components/login.js` (https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/login.js#L21).

It has been removed for security reasons from the repository. You can create an application at https://github.com/settings/developers and use that `Client ID` and `Client Secret` for development purposes. Let me know if you have any issues!

**Comment by mdibaiee** [comment]
@ekonstantinidis Thanks for your respones! It seems to work now, may we have this in README?

Also after adding Client ID and Client Secret I had to logout and login back.

Thank you for Gitify! :+1:

**Comment by ekonstantinidis** [comment]
Awesome @mdibaiee! Will add it to the readme soon! :tada:

**Comment by ekonstantinidis** [comment]
Hey @mdibaiee ! I've added these in the README :+1:

**Comment by mdibaiee** [comment]
@ekonstantinidis Great, thank you! I noticed this using gitify. :sunglasses:

**Comment by ekonstantinidis** [comment]
Awesome :smile:
